// ============================================================================
// Configuration Service - Read/write .conductor/config.yml file
// ============================================================================

import { mkdir } from 'node:fs/promises';
import { YAML } from 'bun';

const CONFIG_DIR = '.conductor';
const CONFIG_FILENAME = `${CONFIG_DIR}/config.yml`;

export type AgentType = 'claude' | 'opencode';

export interface ConductorConfig {
  // Tiger service ID to use as the default parent for database forks
  // null = explicitly "none" (skip DB fork by default)
  // undefined = not set (use tiger CLI default)
  tigerServiceId?: string | null;

  // Default agent to use (claude or opencode)
  agent?: AgentType;

  // Default model to use for the selected agent
  model?: string;
}

/**
 * Read the .conductor/config.yml file from the current directory
 * Returns undefined if the file doesn't exist
 */
export async function readConfig(): Promise<ConductorConfig | undefined> {
  const file = Bun.file(CONFIG_FILENAME);
  if (!(await file.exists())) {
    return undefined;
  }

  const content = await file.text();
  const parsed = YAML.parse(content);

  // Handle empty file or invalid YAML
  if (!parsed || typeof parsed !== 'object') {
    return {};
  }

  return parsed as ConductorConfig;
}

/**
 * Write the .conductor/config.yml file to the current directory
 * Creates the .conductor directory if it doesn't exist
 */
export async function writeConfig(config: ConductorConfig): Promise<void> {
  // Ensure .conductor directory exists
  await mkdir(CONFIG_DIR, { recursive: true });
  await Bun.write(
    CONFIG_FILENAME,
    `# Conductor configuration
# Generated by 'conductor init'
# https://github.com/timescale/conductor
---
${YAML.stringify(config, null, 2)}
`,
  );
}

/**
 * Get the configured tiger service ID, if any
 * Returns:
 *   - string: explicitly configured service ID
 *   - null: explicitly set to "none" (skip DB fork)
 *   - undefined: not configured (use default behavior)
 */
export async function getConfiguredServiceId(): Promise<
  string | null | undefined
> {
  const config = await readConfig();
  if (!config) {
    return undefined;
  }
  return config.tigerServiceId;
}
